version: '3.7'

services:

# EUREKA
  eureka-server:
    image: phambaophuc/mmv1-eureka-server:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - my-network

# ZIPKIN
  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      - my-network

networks:
  my-network:

volumes:
  db_data:
